version: '3'

services:
  argos:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $ARGOS_FILE:/app/mission.argos:rw
    environment:
      - DISPLAY=unix:0
    devices:
      - /dev/snd:/dev/snd
    privileged: true
    command: /opt/argos/AutoMoDe/bin/automode_main_bt -c /app/mission.argos --bt-config --nroot 3 --nchildroot 1 --n0 0 --nchild0 2 --n00 6 --c00 5 --p00 0.26 --n01 5 --a01 0 --rwm01 5 --p01 0
    stdin_open: true
    tty: true
