version: '3'

services:
  argos-container:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_QPA_PLATFORM=wayland
    volumes:
      - ./argos_mount:/app
      - "$HOME/.Xauthority:/root/.Xauthority:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    network_mode: host
    command: /opt/argos/AutoMoDe/bin/automode_main_bt -c /app/mission.argos --bt-config --nroot 3 --nchildroot 1 --n0 0 --nchild0 2 --n00 6 --c00 5 --p00 0.26 --n01 5 --a01 0 --rwm01 5 --p01 0
